version: '3'
services:
  db:
    restart: unless-stopped
    image: postgres:14-alpine@sha256:90bcf5fca0b62305b1c5418e562b092d482554e1ffe0ebee8f73b9820855bcba
    shm_size: 256mb
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'

  redis:
    restart: unless-stopped
    image: redis:7-alpine@sha256:c1ac6782927e574394225a790b6eb476154d1a16681b1374c62625d9bc324b18
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']

  web:
    build: ./mastodon/
    restart: unless-stopped
    env_file: .env.production
    healthcheck:
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:3000/health || exit 1']
    depends_on:
      - db
      - redis

# This chall is not about https://scumjr.github.io/2023/10/12/from-ssrf-to-rce-on-mastodon-cve-2023-42450/
#  sidekiq:
#    image: tootsuite/mastodon:latest
#   restart: unless-stopped
#    env_file: .env.production
#    command: bundle exec sidekiq
#    depends_on:
#      - db
#      - redis
#    networks:
#      - internal_network
#    volumes:
#      - ./public/system:/mastodon/public/system
#    healthcheck:
#      test: ['CMD-SHELL', "ps aux | grep '[s]idekiq\ 6' || false"]
